using System.Globalization;

namespace CodexDuo.Windows.Core;

public sealed class Localizer
{
    private static readonly Dictionary<string, Dictionary<string, string>> Values = new(StringComparer.Ordinal)
    {
        ["en"] = new()
        {
            ["accounts"] = "Accounts",
            ["active"] = "Active",
            ["unavailable"] = "Unavailable",
            ["refresh"] = "Refresh Now",
            ["settings"] = "Settings",
            ["quit"] = "Quit",
            ["appearance"] = "Appearance",
            ["language"] = "Language",
            ["interval"] = "Automatic refresh",
            ["startup"] = "Open Codex Duo at sign-in",
            ["trayGuideHeading"] = "Tray icon",
            ["trayGuideTitle"] = "Keep Codex Duo visible",
            ["trayGuideBody"] = "Pin the icon to the notification area so account usage is always one click away.",
            ["trayGuideSteps"] = "Windows 11: expand Other system tray icons. Windows 10: open Select which icons appear on the taskbar. Then turn on Codex Duo.",
            ["openTaskbarSettings"] = "Open Taskbar Settings",
            ["taskbarSettingsOpened"] = "Taskbar settings opened. Turn on Codex Duo under other system tray icons.",
            ["taskbarSettingsFailed"] = "Windows taskbar settings could not be opened.",
            ["add"] = "Add Account…",
            ["rename"] = "Rename…",
            ["remove"] = "Remove…",
            ["apply"] = "Apply",
            ["dependency"] = "codex-auth is unavailable. Install: npm install -g @loongphy/codex-auth@next",
            ["empty"] = "No accounts are configured. Add an account, finish login, then refresh.",
            ["fiveHour"] = "5 HOUR",
            ["weekly"] = "WEEKLY",
            ["remaining"] = "remaining",
            ["general"] = "General",
            ["dependencyReady"] = "codex-auth is ready",
            ["none"] = "No accounts",
            ["accountCount"] = "{0} accounts",
            ["install"] = "Copy Install Command",
            ["system"] = "System",
            ["light"] = "Light",
            ["dark"] = "Dark",
            ["off"] = "Off",
            ["everyMinute"] = "Every minute",
            ["everyMinutes"] = "Every {0} minutes",
        },
        ["zh-Hans"] = new()
        {
            ["accounts"] = "账户",
            ["active"] = "当前",
            ["unavailable"] = "不可用",
            ["refresh"] = "立即刷新",
            ["settings"] = "设置",
            ["quit"] = "退出",
            ["appearance"] = "外观",
            ["language"] = "语言",
            ["interval"] = "自动刷新",
            ["startup"] = "登录时启动 Codex Duo",
            ["trayGuideHeading"] = "托盘图标",
            ["trayGuideTitle"] = "让 Codex Duo 始终显示",
            ["trayGuideBody"] = "将图标固定在任务栏通知区域，随时一键查看账户用量。",
            ["trayGuideSteps"] = "Windows 11：展开“其他系统托盘图标”；Windows 10：打开“选择哪些图标显示在任务栏上”。然后开启 Codex Duo。",
            ["openTaskbarSettings"] = "打开任务栏设置",
            ["taskbarSettingsOpened"] = "已打开任务栏设置。请在“其他系统托盘图标”中开启 Codex Duo。",
            ["taskbarSettingsFailed"] = "无法打开 Windows 任务栏设置。",
            ["add"] = "添加账户…",
            ["rename"] = "重命名…",
            ["remove"] = "移除…",
            ["apply"] = "应用",
            ["dependency"] = "codex-auth 不可用。安装：npm install -g @loongphy/codex-auth@next",
            ["empty"] = "尚未配置账户。添加账户并完成登录，然后刷新。",
            ["fiveHour"] = "5 小时",
            ["weekly"] = "每周",
            ["remaining"] = "剩余",
            ["general"] = "通用",
            ["dependencyReady"] = "codex-auth 已就绪",
            ["none"] = "没有账户",
            ["accountCount"] = "{0} 个账户",
            ["install"] = "复制安装命令",
            ["system"] = "跟随系统",
            ["light"] = "浅色",
            ["dark"] = "深色",
            ["off"] = "关闭",
            ["everyMinute"] = "每分钟",
            ["everyMinutes"] = "每 {0} 分钟",
        },
        ["zh-Hant"] = new()
        {
            ["accounts"] = "帳戶",
            ["active"] = "目前",
            ["unavailable"] = "無法使用",
            ["refresh"] = "立即重新整理",
            ["settings"] = "設定",
            ["quit"] = "結束",
            ["appearance"] = "外觀",
            ["language"] = "語言",
            ["interval"] = "自動重新整理",
            ["startup"] = "登入時啟動 Codex Duo",
            ["trayGuideHeading"] = "系統匣圖示",
            ["trayGuideTitle"] = "讓 Codex Duo 永遠顯示",
            ["trayGuideBody"] = "將圖示固定在工作列通知區域，隨時一鍵查看帳戶用量。",
            ["trayGuideSteps"] = "Windows 11：展開「其他系統匣圖示」；Windows 10：開啟「選取要顯示在工作列上的圖示」。然後開啟 Codex Duo。",
            ["openTaskbarSettings"] = "開啟工作列設定",
            ["taskbarSettingsOpened"] = "已開啟工作列設定。請在「其他系統匣圖示」中開啟 Codex Duo。",
            ["taskbarSettingsFailed"] = "無法開啟 Windows 工作列設定。",
            ["add"] = "新增帳戶…",
            ["rename"] = "重新命名…",
            ["remove"] = "移除…",
            ["apply"] = "套用",
            ["dependency"] = "codex-auth 無法使用。安裝：npm install -g @loongphy/codex-auth@next",
            ["empty"] = "尚未設定帳戶。新增帳戶並完成登入，然後重新整理。",
            ["fiveHour"] = "5 小時",
            ["weekly"] = "每週",
            ["remaining"] = "剩餘",
            ["general"] = "一般",
            ["dependencyReady"] = "codex-auth 已就緒",
            ["none"] = "沒有帳戶",
            ["accountCount"] = "{0} 個帳戶",
            ["install"] = "複製安裝命令",
            ["system"] = "跟隨系統",
            ["light"] = "淺色",
            ["dark"] = "深色",
            ["off"] = "關閉",
            ["everyMinute"] = "每分鐘",
            ["everyMinutes"] = "每 {0} 分鐘",
        },
        ["ja"] = new()
        {
            ["accounts"] = "アカウント",
            ["active"] = "使用中",
            ["unavailable"] = "利用不可",
            ["refresh"] = "今すぐ更新",
            ["settings"] = "設定",
            ["quit"] = "終了",
            ["appearance"] = "外観",
            ["language"] = "言語",
            ["interval"] = "自動更新",
            ["startup"] = "サインイン時に起動",
            ["trayGuideHeading"] = "トレイ アイコン",
            ["trayGuideTitle"] = "Codex Duo を常に表示",
            ["trayGuideBody"] = "通知領域にアイコンを固定し、アカウント使用量をすぐ確認できます。",
            ["trayGuideSteps"] = "Windows 11 では「その他のシステム トレイ アイコン」、Windows 10 では「タスク バーに表示するアイコンを選択します」を開き、Codex Duo をオンにします。",
            ["openTaskbarSettings"] = "タスク バー設定を開く",
            ["taskbarSettingsOpened"] = "タスク バー設定を開きました。Codex Duo をオンにしてください。",
            ["taskbarSettingsFailed"] = "Windows のタスク バー設定を開けませんでした。",
            ["add"] = "アカウントを追加…",
            ["rename"] = "名前を変更…",
            ["remove"] = "削除…",
            ["apply"] = "適用",
        },
        ["ko"] = new()
        {
            ["accounts"] = "계정",
            ["active"] = "활성",
            ["unavailable"] = "사용 불가",
            ["refresh"] = "지금 새로 고침",
            ["settings"] = "설정",
            ["quit"] = "종료",
            ["appearance"] = "모양",
            ["language"] = "언어",
            ["interval"] = "자동 새로 고침",
            ["startup"] = "로그인할 때 시작",
            ["trayGuideHeading"] = "트레이 아이콘",
            ["trayGuideTitle"] = "Codex Duo 항상 표시",
            ["trayGuideBody"] = "알림 영역에 아이콘을 고정하여 계정 사용량을 바로 확인하세요.",
            ["trayGuideSteps"] = "Windows 11에서는 '기타 시스템 트레이 아이콘', Windows 10에서는 '작업 표시줄에 표시할 아이콘 선택'을 열고 Codex Duo를 켜세요.",
            ["openTaskbarSettings"] = "작업 표시줄 설정 열기",
            ["taskbarSettingsOpened"] = "작업 표시줄 설정을 열었습니다. Codex Duo를 켜세요.",
            ["taskbarSettingsFailed"] = "Windows 작업 표시줄 설정을 열 수 없습니다.",
            ["add"] = "계정 추가…",
            ["rename"] = "이름 바꾸기…",
            ["remove"] = "제거…",
            ["apply"] = "적용",
        },
        ["es"] = new()
        {
            ["accounts"] = "Cuentas",
            ["active"] = "Activa",
            ["unavailable"] = "No disponible",
            ["refresh"] = "Actualizar ahora",
            ["settings"] = "Ajustes",
            ["quit"] = "Salir",
            ["appearance"] = "Apariencia",
            ["language"] = "Idioma",
            ["interval"] = "Actualización automática",
            ["startup"] = "Abrir al iniciar sesión",
            ["trayGuideHeading"] = "Icono de la bandeja",
            ["trayGuideTitle"] = "Mantén Codex Duo visible",
            ["trayGuideBody"] = "Fija el icono al área de notificación para consultar el uso con un clic.",
            ["trayGuideSteps"] = "En Windows 11 abre Otros iconos de la bandeja del sistema; en Windows 10, Seleccionar los iconos que aparecerán en la barra de tareas. Activa Codex Duo.",
            ["openTaskbarSettings"] = "Abrir configuración",
            ["taskbarSettingsOpened"] = "Se abrió la configuración. Activa Codex Duo entre los otros iconos de la bandeja.",
            ["taskbarSettingsFailed"] = "No se pudo abrir la configuración de la barra de tareas.",
            ["add"] = "Añadir cuenta…",
            ["rename"] = "Renombrar…",
            ["remove"] = "Eliminar…",
            ["apply"] = "Aplicar",
        },
        ["fr"] = new()
        {
            ["accounts"] = "Comptes",
            ["active"] = "Actif",
            ["unavailable"] = "Indisponible",
            ["refresh"] = "Actualiser",
            ["settings"] = "Réglages",
            ["quit"] = "Quitter",
            ["appearance"] = "Apparence",
            ["language"] = "Langue",
            ["interval"] = "Actualisation automatique",
            ["startup"] = "Ouvrir à la connexion",
            ["trayGuideHeading"] = "Icône de notification",
            ["trayGuideTitle"] = "Garder Codex Duo visible",
            ["trayGuideBody"] = "Épinglez l’icône dans la zone de notification pour consulter l’utilisation en un clic.",
            ["trayGuideSteps"] = "Sous Windows 11, ouvrez Autres icônes de la barre d’état système ; sous Windows 10, Sélectionner les icônes à afficher dans la barre des tâches. Activez Codex Duo.",
            ["openTaskbarSettings"] = "Ouvrir les paramètres",
            ["taskbarSettingsOpened"] = "Les paramètres sont ouverts. Activez Codex Duo parmi les autres icônes de notification.",
            ["taskbarSettingsFailed"] = "Impossible d’ouvrir les paramètres de la barre des tâches.",
            ["add"] = "Ajouter un compte…",
            ["rename"] = "Renommer…",
            ["remove"] = "Supprimer…",
            ["apply"] = "Appliquer",
        },
        ["de"] = new()
        {
            ["accounts"] = "Konten",
            ["active"] = "Aktiv",
            ["unavailable"] = "Nicht verfügbar",
            ["refresh"] = "Jetzt aktualisieren",
            ["settings"] = "Einstellungen",
            ["quit"] = "Beenden",
            ["appearance"] = "Darstellung",
            ["language"] = "Sprache",
            ["interval"] = "Automatisch aktualisieren",
            ["startup"] = "Bei Anmeldung öffnen",
            ["trayGuideHeading"] = "Infobereich-Symbol",
            ["trayGuideTitle"] = "Codex Duo immer anzeigen",
            ["trayGuideBody"] = "Heften Sie das Symbol an den Infobereich an, um die Nutzung mit einem Klick zu sehen.",
            ["trayGuideSteps"] = "Öffnen Sie unter Windows 11 Andere Taskleistensymbole, unter Windows 10 Symbole für die Anzeige auf der Taskleiste auswählen, und aktivieren Sie Codex Duo.",
            ["openTaskbarSettings"] = "Taskleisteneinstellungen öffnen",
            ["taskbarSettingsOpened"] = "Die Taskleisteneinstellungen wurden geöffnet. Aktivieren Sie dort Codex Duo.",
            ["taskbarSettingsFailed"] = "Die Taskleisteneinstellungen konnten nicht geöffnet werden.",
            ["add"] = "Konto hinzufügen…",
            ["rename"] = "Umbenennen…",
            ["remove"] = "Entfernen…",
            ["apply"] = "Anwenden",
        },
    };

    public Localizer(string language)
    {
        Language = ResolveLanguage(language);
    }

    public string Language { get; }
    public string this[string key] => Values.GetValueOrDefault(Language)?.GetValueOrDefault(key)
        ?? Values["en"].GetValueOrDefault(key)
        ?? key;

    public static string ResolveLanguage(string language)
    {
        if (language != "system" && Values.ContainsKey(language)) return language;
        var code = CultureInfo.CurrentUICulture.Name;
        if (code.StartsWith("zh-Hant", StringComparison.OrdinalIgnoreCase) || code.StartsWith("zh-TW", StringComparison.OrdinalIgnoreCase) || code.StartsWith("zh-HK", StringComparison.OrdinalIgnoreCase)) return "zh-Hant";
        if (code.StartsWith("zh", StringComparison.OrdinalIgnoreCase)) return "zh-Hans";
        foreach (var candidate in new[] { "ja", "ko", "es", "fr", "de" })
        {
            if (code.StartsWith(candidate, StringComparison.OrdinalIgnoreCase)) return candidate;
        }
        return "en";
    }
}
